// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3XMTNxD/VzQqD9DeV0Io5V46IUnBM5RmMH0CN7O+W9uCO0lIujjG4/+9o4/z150h",
	"mZaUhz5xSLva3d/+9iNe0kLUUnDkRtN8SXUxwxrc54VSQtmPEnWhmDRMcJrTN7+dkae/ZE+JVGJcYU1K",
	"NMAqTSMqlZCoDEPt1ey5/TILiTSn2ijGp3QVUca1AV6gvZwIVYOhOW0UixVOUKG9ibpa2oBp9I4O4+bx",
	"8UaWcYNTVFbYMFNhr3F/cHvDq4gq/NQwhSXN3/nb9v3RWlqMP2Bh7PsvESoz6wLnz0mIYh8tCV4Hb6CW",
	"1nM68+9Y61D+wasFzY1q8AAw2Ke86IOxjX8j/Dg2DFVcYi1ijeqaFRhLJa5ZiSopizphIl17cxC2r7jZ",
	"D6N3PfLhd9CM6E0MKGOFWjTK80WCMai4to8Ep0YRlVWjoFoHbvHVjE8rNBZ775A9aCpQ29gGe3dAwAYy",
	"NFB87Gb4lPh3iH3HJrr4SB7OcRwRkDIi5fhRJ+2FQjB4ZVi9y8kSDMbu9Bb5Z2XXlz85+9RgcGJw7iG2",
	"wNGc/vUO4s9Z/Gz0MHzEo2UW/Xy0as8f/frgNnY5eK/3eN7UwGOrDOOq9cCJHvAhDl8/7prvmGtLZK8f",
	"BW4Qd30LrxtZ/lPI97jsgrszeR0wOl26f69Yudrhsb+lO6x1Z3cjrVdZc/YV08b5sUNCjjfmSsIUr4z4",
	"iLy3awZ/8iVlBmv38UDhhOb0h3QzQtIwP1JfIetuQ0EpWDg/9vrlyo2DiXDFILiBwjnoqUXPz34nl0oE",
	"PBvlKtwYqfM0nTIza8ZJIeq0LGobuRVLv4SKdWiXPdZAkCKtFJkI1VbybvluFbZO3vPTi8vYxl4x4Ia8",
	"uRi+JaeXg+Q9pxGtWIFc41YspxKKGZLjJOuEMp/PE3DXiVDTNOjq9NXg7OL18CI+TrJkZupqa7DRx/Fb",
	"6+C59WgYIrhsIzi9HNCIXqPSPsyjJEsyqy0kcpDM6idZchI6r0tn2+DyJZ2i6Ss00yiuiZkhmW3PMiIm",
	"7jDgSJ0VBVZtUNKcvkDzcjPLtBQ2Nvv+cZa1aUfuLIKUFSucavpBC75ZSb5GuJdtd+6kuAWHadJORSuk",
	"m7oGtdgM5rMZ+uqCqavP8OLICqcb+vdiY+uq2/w1mTMzI8JJQUUkTBl3wXUwsg8M25KXoKBGg8r6saTM",
	"WvjUoLLjPJCphhtfsZp9dnN0DVKJE2gqQ/MnWdRdlGq4YXVT0/woyyJaMx7+112hVlG/5a0+sW12v0OO",
	"vmGuN62sL91NUaDWluwnX7QZ9tef7mbbb8U9dp9DSexQQO22wCf3aXvA7VSBypUgKoJBcJvljqJrirUk",
	"DwcjO16F7mH2mVtQCBCO8y7DOzz24sNwF/B4LsrFv5t8D8JmBtspveow7uhbGN1jm9tu/BZX/tecO8me",
	"3Z/tM8EnFSu+T7IH1rY87LB909LD/jUoV577FZqenfbcnRM4wHp/3Vrra99hOQ09NJik+xTebqh3Xte/",
	"3oFPDgUWmHtyf0l8LQyZiIaX3yV9QroP0ifq3wJeoGkpQsYL/1dXZxX67lmS3UPX3J7R/7MusM7S53DH",
	"sqJO1/Nl75eHywG5PoJKzuBo/ddFCpKl61Ob6fDqgV+mirAAB/q1G3W0Lx62AM/zik2wWBQVbhSDz6vR",
	"6u8AAAD//wLEcgteFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
