// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW3PbNhb+K2ewfbC3FCXFidtqH3YcW2004zoaX6YPkdeFyCMJDQkgABhZzei/7+BC",
	"iRRpWdk22e7MvlHkAc79Oxd9IonIpeDIjSaDT0QnC8ypezyT8pahupGY2J8p6kQxaZjgZGA/Ziyh9hcY",
	"hiqGO40a3p6PgOV0jjGJiFRCojIM3XULY+SDFMo0LxsrllO1gje3t2OwJGAWCLTCImPaINcgeDzhdxpT",
	"mK4c0RKnjj9IJR5XYATMhFpSlYJRdDZjSQwXOKNFZrT9+H3v+1484SQi+EhzmSEZ2FcRyekjy4ucDE5f",
	"vTp5FZGccf+7HxGzkkgGhHGDc1RkHRGnYlOPjfagcIYKeYJWnF1t4ip7korkPaqYia6WivF5IvK84Mys",
	"wu/OTNEcl0K970g0ScY4SwancT9+QTaiaWMprWQcjSW1sn2jcEYG5G/drYe7wb1d69irQLpeR0Thh4Ip",
	"TMngXVDufnO5mP6GibGXnwtuKOOoxsGNNE2Z1Yhm44qvjSpw1/tJeXQTAn/IAR+ZZlOWMbNqeuGNWIJZ",
	"MO0jiWnARylsyBgBieC6yFHpeMI7wAXHAYwDGRdmQyoKo1mKznMb0W2MJai1PWplUZxmAxhub7fUC6EN",
	"CAVJVmiDCoJD7Bl8LM9cI00WdJohzJTIa9zs+W447AOVWyu8I1ZYEpGSsYuh8HhfjacKwU507Ph5xyU1",
	"o7Z5/4IaOqUanwaFkqKKCHSqjaKJAZYiN2zGUGk4Qj5nHCP4iEozwY9B8GwVT/jNGHIqNfjv34bP1rbb",
	"3DrCeB6DFNrMFepv+6fQmRS93gnCNpUyNlVUrbol1aB/euzzvh6Wns8eTTwBHJUXRZCv9IfsuJ7D5dc/",
	"KyMjEjR/XrJAWJenf/qs94PmW05tLh8qJVRThusfz+G773vf2YSYZphDioayTDfM69/bp4ZZGNeG8sTZ",
	"fiZUTg0ZkEKxzgY624ypDTWFrp1h3JxUoLACEoaZDFuZ+xeHM96xnfta3t9mtzdIM7NogSb3HoIWu9aS",
	"1J/Z+nHh77HcafqWZ6sSXFsNg22HV21mLPXfEpuFQuzYvO2kmIuOlnGa5DaVNjI8aaxnhGs3nhc48ko3",
	"bBiRxw5F2VGoRaF8lEhqLLJpe0kQ6j4iMisUzTbqWqtqxucZGmtxL5B9UWRUVS0a+D2rtxX/1hLZBD2T",
	"sunUE3fcFng4WuI0sk8RpNPjGM4VUmO7Aae+Bi0x+Qew1MP+hwLVCiRVNI8gR0NTamjMaY6RrSAa1UdU",
	"cHc3umh2U4m7+cGwvB7IKTVWnRwPCRqWNrW54+xD4doVGF3AkReiM0eOihoMkteEPfZetL4hA/Kvd7Tz",
	"e6/zw/1ReOjcf+pFp/11+f74n98cIlvJ4lncrPjm5/LMOtok0w5yhXgC+7mp3fEhkkklPrIU1cOChaZ5",
	"XxvUwAbLkyX4UOZgXcAb/xXsVzjKC21gahsDhdbZqB6olA82Uo8rrUHL50pKVUAiVO2D7OlKfA1yaZa9",
	"nZHBu8MdcuPPru93zbqOSCHTPx7BS5w+IE+lYLxlrri7vrStg7LdVm1aiEAKWWQuoJcL5ED5pjuD0dh2",
	"g/QjZZlt0SbcNxyCw1uJ/GbBZgaWzCyAwqWg6Wua2TqmjmO4Ypm/zrWNoQFMBbrecsKp1mze4HVUaIRf",
	"3xdTTEzmetZOGGF+BVskkaahdfk8nHXO/mxgreAhlVJ3P+3EFkvXNdTdoSc1sK1/PAR0d07sgu8l087N",
	"dSzk+GgeJJ3jgxHvkbdX/Joa7hgzmOvPgZdt5SRUKbpy4jXyuxWQGjJndIrZHvB4smmpcLLgW6/i+Wo7",
	"IxI3U10in1sgPD1xI1X5s/8EZHfC09/raL0/0pwc98+Y4mYDIzuLhPlc4dxlokcaEDOXP9uyWkG68fDq",
	"YnT1E4nI9d3VlX/68Wx0ObwgEbkYXg5vhxet0FeHtYYUt5u4A21UkZhCIRylodcOJX2J0+NGIaa+JdgX",
	"Q9VFyjoi5a3PHWvMWx7vnjv2C063J3Y8tWEdEW9Xe1+r5yrTSCN2LUYdnkH1pcFBKVRVoeGqXwKGP79x",
	"+g+2NLZA+KbgqSVNOVna8elxQDPpp6ivuYhZu/FpJjZ7lcSBoocDcnH+M4yVCGhfKNcbGyP1oNudM7Mo",
	"pnEi8m6a5B3pybonVSz2DUin7HJcxNYn0POfIVBBSeUMGDK23gSDvdX+0vGEnw3HHWuEjFFu4Hp4cwtn",
	"45GvbhlLkPusCJqcSZosEF7EvYYiy+Uypu5zLNS8G87q7uXofHh1M+y8iHvxwuRZZQwkJx1rbLiw8pRt",
	"1riU/2w8qszCA9KPe3HPnhYSOZXMno978cswsbj46lLJuh/7NJML2u/uVsLBJzLHlqbE1rDSVBvb+IZC",
	"SF8IQNI5425XSJwEyj2P0nC8iqtujLQjBBpU2nVnzLJxwwUpi4QtBb5Eava7G79c/Hnp3HqUDF71ouZU",
	"vVnL9Xu9/Uu5ddTOuVKYq2x3S4prEbUU1o32+4ter4xv9L1dZYPa/U373cj2vkOLuGshXArtNN5FkqDW",
	"1uUv97IOO49vP08Ev0lp4fuapm4+RO2g79XX5D0Kq8Jy1MRAGBFd5DlVqzJcfXl06RNCztC56xfroXhv",
	"xyOhW6I+TMIUOC53ox+OLl7XS2w95P3ZWifWiPkdiC8TKckYctOxvTCbMUztTFti/TZhLe8YRjO3Ag6Q",
	"lkYTbqmCaZYsy6CcE4H6qRx+sc3+VJhFfSIGylM75VNlz5towllqZwp3nxEKUyjXX8DSeMIn/Nrjfm4d",
	"B0fSGno47vRfvDgeTHgH+p3TE0gWVNHEqgyZ4HP7/sZQtZlGMrFElVCNkKHt7UAoSNmcGUsZyrBbtDYo",
	"dQS8yKfuwcq+WMkFcrfoHvLU37+905M60G5LeJbWEv3zm9B9e4NW2HDZ81qkqy+CGD5ztoU5zK87aNX/",
	"gryf7FVt8vhNUPrfBq6XvR++Hu9zwWcZS/6aiBmgro6ZeyBzHe3vJMpN5FMNxTWaQnGPLovqgrmcpEKz",
	"1sDVn9C82S6Yv1DtfVOuUZsVN/RgTEO5qq4bMmzLzxeYvK/YL9x4gOH88iKYepSuve0yNG3/+Lj3QOtz",
	"Z91gnmZ/IXKI6JaPG0CsS0F2saQKln8OHtZc+fIpXQNkvPx62XMlDMxEwdO/ZN6GCDg4b6P2dPwJTS2K",
	"YLqC0UVb8v2PBVLvq1W4Wi/+//gM8WkD6/CiEv5paO+P943Cm1m76/b2gcET/2QmAZtDgJZgH+35jyxj",
	"M0xWSYbbY3Xh1/frfwcAAP//8X7zHpYkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
