// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZXW/buNL+KwTfvUjeSrLdtNmubw7S2NsaSFOjSbEXjU+WlsY2NxLJklQcb+D/fsAP",
	"yfpK4uBsc/YA506WOJzhzDMzz9D3OOaZ4AyYVnh4j1W8gozYxxMhLinICwGx+ZmAiiUVmnKGh+ZjSmNi",
	"fiFNQUboqwKFPp9OEM3IEiIcYCG5AKkp2O3s6/ZGpQSSsAAJLAa04BLpFSCyU2L2gzuSiRTwECc8vgEZ",
	"Ud5TQlK2jHmW5Yzqjf8dLiTJYM3lTShAxyllNB4eR4PoNQ6w3gizh9JmJd4GmIE2S41tP0lY4CH+v97O",
	"Kz3vkp5xxrlfut0GWML3nEpI8PCbP9ys3JzP/4BYm81POdOEMpBTLrVRQZKEmhORdFrxj5Y5ND0WF6LX",
	"wsuWHnjXf9cPcEbuaJZneHj89u3R2wBnlLnfg9IQyjQsQRpLbqmic5pSvWlH4SNfI72iChlNiCoEd4Ir",
	"SJDmKOZM5RlIFV2xEDHOYIimfhnjulzKc61oAjZypelISB6DUkbU2CIZSYdovNvdrF5xpRGXKE5zpUEi",
	"HxAjA3eFzBcg8YrMU0ALybOaNiPf88JXzCCFGS98w8ZYHOBCscWQf5xV8VRZ0EBHI86NkNSc2hX9EdFk",
	"ThQ8nEjFimoWkbnSksQa0QSYpgsKUqEDYEvKIEC3IBXl7BBxlm6iK3YxRRkRCrnvr/xn49tdbh1AtIyQ",
	"4EovJahXg2MUXuX9/hGgXSqldC6J3PSKVcPB8WFk3VmHpdPzyEncAnRQbBSgbKO+p4f1HC6+/lUZGWB/",
	"8qct8wvr9gyOn4y+P/lOU1fIx1Jy2bbhy6+n6Od3/Z9NQsxTyFACmtBUtdzr3punllsoU5qw2Pp+wWVG",
	"NB7iXNKwLJ1dzlSa6FzVZCjTR5VSWCkSmuoUOpW7F/srbvjOfi327/LbRyCpXnWUJvse+VM0vSWIk9nF",
	"ceX2MdpJ8pmlm6K4djoGuoQ3XW4szr9brFcSIDR5GyaQ8VCJKIkzk0qlDQ866wnjup3nDA7coVs+DPBd",
	"SECEEhTPpUOJINpUNmU28UbNAizSXJK0PK7xqqJsmYI2HncGmRd5SmTVo17fk+c25l+aRSZBT4TooA/o",
	"yG6AzAamz6ODNcwD8xSgZH7YinMsgWi41jSrgzAh2piSwT4Bp0nbkq+Mfs8t1UCTETpQIG9BhktgIImG",
	"xDWbDDRJiCYRIxkcuggYv+Ih/uc3Ev7ZD3+ZHfiHcHbfD44H2+L94T9+2se2QsWTNa/i10+FzDYoE6FR",
	"dTwWkPncPt3hPpYJyW9pAvJ6RT1JfIzCtPLa6KQxXBf5Uzfwwn1F5is6yHKl0dw0dQkm2CCviRDXBiSH",
	"lbbe8bmSDpUE9x13L3/a9lwrlyRNPy/w8Nv+AblwsttZ063bAOci+fcRvIb5NbBEcMp0B5a/nJm2Lw1T",
	"ssRoDXPLKwIkuMhTC+j1ChgirGRWaDI1TI7cEpoaenXFHFngDH0WwC5WdKHRmuoVIuiMk+Q9SU0PkocR",
	"Oqep285SPk/eEg6WF14xohRdtnQd5ArQ7zf5HGKdWr4ZLrhcE5n8jkyDA5J42vG8GlkmkI/7s+tjpawR",
	"IVTvvgEzmmxrxbOxHtdqZv3jPrWzIdGsoWdU2YjXyyKDO30tyBKuNb8B1t24a8dws5iGTD2n0uwaICZS",
	"ko01r5XqnbWpZXNK5pA+Ukce5B4VTaYO15txttmNetiORmfAlqYmHh/Zyaj4OXigeof+6f/rhftx0Fk7",
	"Zk+44qKsKI0muFxKWNqkdEUH8YVNJd8bHXCKojcdn48m5x9wgL98PT93T7+eTM7GIxzg0fhsfDkedVbB",
	"eoVrWXFZ4g4pLfNY5xLQQeIps2/Ja+joycR19scwVL1D2Aa42PUpsdbY5ErfU2K/wXwn0YhUqTrAzq9m",
	"v87IVYaKFnZNudo/g+qz/14pVD1CK1S/+XL+Qy5bTK9w/OChu5ZiQDRT0N2QpMINQy95n7K1U9CCl9cj",
	"sS2Krhzg0eknNJXcV/tcWoqrtVDDXm9J9SqfRzHPekmchcIt6x1Va7HjImFBeCxi64Pk6SfkV6FilXWg",
	"z9g6iS3JrYqu2Ml4GhonpJQwjb6MLy7RyXTiGl1KY2AuK/xJTgSJV4BeR/3WQdbrdUTs54jLZc/Lqt7Z",
	"5HR8fjEOX0f9aKWztDLN4aPQOBuNjD0F45oW9p9MJ5WRdogHUT/qG2kugBFBjXzUj974wcPiq2D6w3u8",
	"BN3FO3UumXK3M9UBrihx3ovYapH2im+S4CH+APrjboBTgpuzmf1f9/tF0MFxn8rtYO8P5eZ+h62nkPex",
	"GFNaAS6cQxUqRkGzSOVZRuRmN42eriC+MdgnS8sd/I4zs7jXJAYPOcm09OYcpBzV4sL1RSTIkjJ7xpar",
	"jHi1zdjhmEiSgQapLG+lRs33HKSZaD20MnLnGIOif9qhsnRZAguSpxoP3/aD9l1Bedk46Pcfv2rcBt2a",
	"KzylqrbZYWc/MPItRtWFgTyOQSmTAW8eVe1vcl49zwR3P9Sh9z1JkKmBoGwnePuSuif+AtR3AAR+YRX6",
	"Fq6OLdhq4iFXpEAdijMzOHLVgfpTO8kjghis27cAo/d1xlGHvJOtEdMW5hsdr0gkP+CbYk0TyAQ3XkX2",
	"WsElVxdiaVJD6rOn/k5o2wi/58nmh6DaRXfXS/302ciowQ/U/SC9NCFw9zjJfzq53vR/eTndp5wtUhr/",
	"PbPap2M9rx9J644G5ydlv2iSbF3Sp6C7/iWw7xGpDzn1NHdrHk9zm6720qvM1roVuJkFf30m11LqzUNn",
	"9WB/83JxP+caLXjOkr8l4jwC9kZc0M2ePoCuoQjNN2gy6iKU/2VA6r9Yba4xnf/h0+PTAGv/cuhvuLvZ",
	"x8l0gm4HJBUrMigHuR4RtFe+NQDwmz/wz1fsZw0PzmJ4CZrLK6mQ0gXEmziFnVjd8O1s+68AAAD//x3N",
	"oOT6IQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
