// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ContainerPortVisibility.
const (
	External ContainerPortVisibility = "external"
	Internal ContainerPortVisibility = "internal"
	None     ContainerPortVisibility = "none"
)

// Valid indicates whether the value is a known member of the ContainerPortVisibility enum.
func (e ContainerPortVisibility) Valid() bool {
	switch e {
	case External:
		return true
	case Internal:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for ThreeTierAppServiceType.
const (
	ThreeTierAppDemo ThreeTierAppServiceType = "three_tier_app_demo"
)

// Valid indicates whether the value is a known member of the ThreeTierAppServiceType enum.
func (e ThreeTierAppServiceType) Valid() bool {
	switch e {
	case ThreeTierAppDemo:
		return true
	default:
		return false
	}
}

// Defines values for ThreeTierAppStatus.
const (
	DELETED ThreeTierAppStatus = "DELETED"
	FAILED  ThreeTierAppStatus = "FAILED"
	PENDING ThreeTierAppStatus = "PENDING"
	RUNNING ThreeTierAppStatus = "RUNNING"
)

// Valid indicates whether the value is a known member of the ThreeTierAppStatus enum.
func (e ThreeTierAppStatus) Valid() bool {
	switch e {
	case DELETED:
		return true
	case FAILED:
		return true
	case PENDING:
		return true
	case RUNNING:
		return true
	default:
		return false
	}
}

// AppTierSpec Application tier. Uses OCI image.
type AppTierSpec struct {
	// HttpPort Primary HTTP port the application listens on.
	// Used by the web tier proxy to forward traffic. Defaults to 8080.
	HttpPort *int `json:"http_port,omitempty"`

	// Image OCI image reference for the application.
	Image   string       `json:"image"`
	Network *TierNetwork `json:"network,omitempty"`
}

// ContainerPort defines model for ContainerPort.
type ContainerPort struct {
	ContainerPort int `json:"container_port"`

	// Visibility How this port is exposed to consumers.
	// - none: Port is not exposed outside the container process
	// - internal: Exposed to the host or cluster network
	// - external: Reachable from outside the host/cluster
	Visibility           ContainerPortVisibility `json:"visibility"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// ContainerPortVisibility How this port is exposed to consumers.
// - none: Port is not exposed outside the container process
// - internal: Exposed to the host or cluster network
// - external: Reachable from outside the host/cluster
type ContainerPortVisibility string

// DatabaseTierSpec Database tier. Uses abstract identifiers (engine, version) only.
// SP maps engine+version to OCI image (e.g. postgres+16 -> docker.io/library/postgres:16).
type DatabaseTierSpec struct {
	// Engine Database engine (postgres, mysql).
	Engine  string       `json:"engine"`
	Network *TierNetwork `json:"network,omitempty"`

	// Version Database engine version.
	Version string `json:"version"`
}

// Error RFC 7807 problem details
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int32  `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// Health Health status
type Health struct {
	Path  *string `json:"path,omitempty"`
	State string  `json:"state"`
	Type  *string `json:"type,omitempty"`
}

// ThreeTierApp 3-tier app (web, app, db). Create requires spec; id from query param, metadata.name, or server UUID.
type ThreeTierApp struct {
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique app ID (server-generated from metadata.name)
	Id       *string               `json:"id,omitempty"`
	Metadata *ThreeTierAppMetadata `json:"metadata,omitempty"`

	// Path Resource path (server-generated)
	Path          *string                 `json:"path,omitempty"`
	ProviderHints *map[string]interface{} `json:"provider_hints,omitempty"`

	// ServiceType Service type (must be three_tier_app_demo)
	ServiceType *ThreeTierAppServiceType `json:"service_type,omitempty"`

	// Spec Three-tier structure (database, app, web)
	Spec       ThreeTierSpec       `json:"spec"`
	Status     *ThreeTierAppStatus `json:"status,omitempty"`
	UpdateTime *time.Time          `json:"update_time,omitempty"`

	// WebEndpoint URL to reach the web tier, populated when an external IP is available
	// (e.g. on OpenShift with a LoadBalancer). Nil when the cluster does not
	// assign an external IP (use `kubectl port-forward` instead).
	WebEndpoint *string `json:"web_endpoint,omitempty"`
}

// ThreeTierAppServiceType Service type (must be three_tier_app_demo)
type ThreeTierAppServiceType string

// ThreeTierAppList defines model for ThreeTierAppList.
type ThreeTierAppList struct {
	NextPageToken *string         `json:"next_page_token,omitempty"`
	ThreeTierApps *[]ThreeTierApp `json:"three_tier_apps,omitempty"`
}

// ThreeTierAppMetadata defines model for ThreeTierAppMetadata.
type ThreeTierAppMetadata struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
}

// ThreeTierAppStatus Aggregated status of the 3-tier app
type ThreeTierAppStatus string

// ThreeTierSpec Three-tier structure (database, app, web)
type ThreeTierSpec struct {
	// App Application tier. Uses OCI image.
	App AppTierSpec `json:"app"`

	// Database Database tier. Uses abstract identifiers (engine, version) only.
	// SP maps engine+version to OCI image (e.g. postgres+16 -> docker.io/library/postgres:16).
	Database DatabaseTierSpec `json:"database"`

	// Web Web tier. Uses OCI image.
	Web WebTierSpec `json:"web"`
}

// TierNetwork defines model for TierNetwork.
type TierNetwork struct {
	Ports *[]ContainerPort `json:"ports,omitempty"`
}

// WebTierSpec Web tier. Uses OCI image.
type WebTierSpec struct {
	// Image OCI image reference for the web server.
	Image   string       `json:"image"`
	Network *TierNetwork `json:"network,omitempty"`
}

// ListThreeTierAppsParams defines parameters for ListThreeTierApps.
type ListThreeTierAppsParams struct {
	MaxPageSize *int32  `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateThreeTierAppParams defines parameters for CreateThreeTierApp.
type CreateThreeTierAppParams struct {
	// Id Optional client-specified ID for the three-tier app. If not provided,
	// the server will generate a UUID. When both metadata.name and id are set,
	// id is the stored instance id.
	//
	// Requirements (per AEP-122):
	// - 1-63 characters long
	// - Start with a lowercase letter or digit
	// - Contain only lowercase letters, numbers, and hyphens
	// - End with letter or number
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateThreeTierAppJSONRequestBody defines body for CreateThreeTierApp for application/json ContentType.
type CreateThreeTierAppJSONRequestBody = ThreeTierApp

// Getter for additional properties for ContainerPort. Returns the specified
// element and whether it was found
func (a ContainerPort) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContainerPort
func (a *ContainerPort) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a *ContainerPort) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["container_port"]; found {
		err = json.Unmarshal(raw, &a.ContainerPort)
		if err != nil {
			return fmt.Errorf("error reading 'container_port': %w", err)
		}
		delete(object, "container_port")
	}

	if raw, found := object["visibility"]; found {
		err = json.Unmarshal(raw, &a.Visibility)
		if err != nil {
			return fmt.Errorf("error reading 'visibility': %w", err)
		}
		delete(object, "visibility")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContainerPort to handle AdditionalProperties
func (a ContainerPort) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["container_port"], err = json.Marshal(a.ContainerPort)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'container_port': %w", err)
	}

	object["visibility"], err = json.Marshal(a.Visibility)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'visibility': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
